### ISSUE TITLE
Regression Testing for AE Explorer v3.0.0

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/aeexplorer#39]
Confirm basic functionality and new features are working as expected in examples shown below:

Examples using v3.0.0 Release Candidate
[Default](http://interactive.it.rhoworld.com/dev/projects/232/ae-table/)

**Basic Functionality (Tested every release)**
- [x] Check all spelling and grammar on the page
- [x] View confidence intervals and tooltips for between-group differences by hovering the mouse over the - Difference Between icons. 
- [x] Expand the dataset to show nested preferred terms by clicking the "+" to the left of each category. 
- [x] Search by terms of interest and then close the search. 
- [x] Confirm that filters on events (e.g. Severity) are working as expected: rates in the table change, but number of observation in the table header do not. 
- [x] Confirm that filters on participants (e.g. Gender) are working as expected: rates in the table and number of observations in the table header both change. 
- [x] Select events based on a minimum incidence threshold
- [x] Confirm that toggling between 'participant' and 'event' views work as expected (there should be more events than participants. 
- [x] Confirm that you can view a detailed listing of events by clicking on the title of a given row in the table, and that the current filters are applied as expected in the detail view. 
- [x] Confirm that the button that closes the detailed listing works as expected.

**New Functionality (Tested in V3.0.0 only)**
- [x] (#4) Confirm that you can filter on participant demographic information (sex, median age, and treatment group when data is unblinded)
- [x] (#5) Confirm that when a series of events is selected, the ability to filter on this detailed view is working as expected
- [x] (#27) Confirm that group columns are sorted alphabetically
- [x] (#32) Confirm that selecting a group variable with multiple categories doesn't crash the browser
- [x] (#43) Confirm that the event counts in the column headers are updating when changes are made to the participant filters

**Comment by brittsikora** [comment]
Regression Testing notes:
- Capitalize the "participant" and "event" toggle options for consistency
- Capitalize "group" in "AE Rate by group"
- There is a blank category in this example - not sure if it's a data issue, but see the image below
![ae_blank_category](https://cloud.githubusercontent.com/assets/14914918/22253899/2bcd5d7c-e221-11e6-9d45-4abf5b2c40d1.JPG)
- Add space around the "Serious" filter options because that box is too small
- Superscript "E" among the filters doesn't convey its purpose - perhaps add a question mark there
- Users have to type in a search term and click on another spot on the screen to complete the search
- No gender filter
- When selecting a minimum incidence threshold, the user has to click on another spot on the screen to complete the action
- "Relationship" filter options not in intuitive order

**Comment by brittsikora** [comment]
Functional testing notes:
Tested #32 and discovered #50

**Comment by jwildfire** [comment]
Good comments all around, @brittsikora. Most are fairly minor issues, so I've assigned them to v3.1.0

**Comment by brittsikora** [comment]
passed testing - closing
